### ISSUE TITLE
Failed at Cinder installation 

### ISSUE THREAD

**Issue by sawantuday** [tigerlinux/openstack-mitaka-installer-ubuntu1604lts#1]
Please find the attached logs for more details ...
[OpenStack install log.txt](https://github.com/tigerlinux/openstack-mitaka-installer-ubuntu1604lts/files/293478/OpenStack.install.log.txt)

```
Applying IPTABLES rules
 * Saving netfilter rules...                                                                                
run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save
                                                                                                     [ OK ]
Unable to establish connection to http://192.168.1.103:8776/v2/d97dfc563ff44f44b8244f9f32186f25/types

Cinder Installation FAILED. Aborting !


Cinder installation failed. Aborting !!
```

**Comment by tigerlinux** [comment]
Hi there,

You have your O/S locale bad configured, and this is affecting python operations regarding the database access. That's a common problem in debian-based installs (and ubuntu is a "very well done" debian) specially in non-us locale installs (happened to me long ago when I started using debian and Ubuntu, as I'm located in Venezuela).

Yo need to set LC_ALL variable to "en_US.UTF-8" in your "/etc/default/locale" file, and restart your session (of better: your server):

LC_ALL="en_US.UTF-8"

This is very common error on debian-based installs. Happens to almost every one, specially if you are not using an US-Based locale. 

Set this variable as instructed, reboot the server, uninstall openstack with ./main-installer.sh uninstall auto, then start over again !

Please note that the install log is shouting this every time it can !.
